version: "3.8"
services:
  myapp:
    build:
      context: .
      dockerfile: Dockerfile
    image: myapp:latest
    volumes:
      - .:/app
    command: ["crond", "-f"]
    secrets:
      - mysecrets
secrets:
  mysecrets:
    external: true

